# Generated by Django 4.0.3 on 2022-03-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BullExteriro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default='')),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=3)),
                ('humitat', models.DecimalField(decimal_places=1, max_digits=3)),
                ('eCO2', models.IntegerField(default='')),
                ('TVOC', models.IntegerField(default='')),
                ('pressio', models.IntegerField(default='')),
            ],
        ),
    ]
